import 'dart:convert';
import 'package:archive/archive.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:titiksha_mobile/core/services/data_import_service.dart';
import 'package:titiksha_mobile/core/services/csv_export_service.dart';
import 'package:titiksha_mobile/data/models/device_status.dart';
import 'package:titiksha_mobile/data/models/client_section.dart';
import 'package:titiksha_mobile/data/models/task_item.dart';
import 'package:titiksha_mobile/data/models/reminder_item.dart';

void main() {
  group('Real-world Import & Export Compatibility Tests', () {
    // 1. ESP32 live /api/backup.json structure
    const esp32LiveJsonBackup = '''
{
  "globalGoal": 36000,
  "brightness": 10,
  "savedAt": "2026-09-12 09:54:48",
  "currentStreak": 5,
  "longestStreak": 12,
  "lastActiveDate": "12 Sep 2026",
  "clients": [
    {
      "id": 5,
      "name": "Reading",
      "totalSecsToday": 7200,
      "reps": 27,
      "history": [
        {"timestamp": "2026-09-12 05:26:59", "date": "12 Sep 2026", "secs": 3600, "reps": 1},
        {"timestamp": "2026-09-11 22:13:59", "date": "11 Sep 2026", "secs": 4000, "reps": 5}
      ]
    },
    {
      "id": 6,
      "name": "Meditation",
      "totalSecsToday": 1800,
      "reps": 3,
      "history": []
    }
  ],
  "tasks": [
    {"id": 1, "text": "Review PR", "stars": 3, "done": false}
  ],
  "reminders": [
    {"id": 1, "text": "Drink water"}
  ]
}
''';

    test('Live ESP32 backup JSON parses correctly', () {
      final res = DataImportService.parseAndValidate(esp32LiveJsonBackup);
      expect(res.isValid, isTrue, reason: res.errorMessage);
      expect(res.format, 'CRANIUM JSON BACKUP');
      expect(res.sectionCount, 2);
      expect(res.sessionCount, 2);
      expect(res.totalDurationSeconds, 7200 + 3600 + 4000 + 1800);
      expect(res.currentStreak, 5);
      expect(res.longestStreak, 12);
      expect(res.sectionNames, ['Reading', 'Meditation']);
      
      // Check synthesized JSON has both totalSecsToday and reps for ESP32 compatibility
      final synth = jsonDecode(res.synthesizedJson) as Map<String, dynamic>;
      final synthClients = synth['clients'] as List<dynamic>;
      final firstClient = synthClients.first as Map<String, dynamic>;
      expect(firstClient['totalSecsToday'], 7200);
      expect(firstClient['reps'], 27);
    });

    // 2. Real Sessions CSV generated by ESP32 and CsvExportService
    const realSessionsCsv = '''
Full_Timestamp,Date,Focus_Section,Duration_Formatted,Duration_Seconds,Reps_Completed,Mastery_Level
"2026-09-12 10:01:18","12 Sep 2026 (TODAY)","Reading","0h 2m 24s",144,27,"LEVEL 0"
"2026-09-11 22:13:59","11 Sep 2026","Meditation","1h 06m 40s",4000,5,"LEVEL 1"
''';

    test('Real Sessions CSV exported from device or app parses correctly', () {
      final res = DataImportService.parseAndValidate(realSessionsCsv);
      expect(res.isValid, isTrue, reason: res.errorMessage);
      expect(res.sectionCount, 2);
      expect(res.sessionCount, 2);
      expect(res.totalDurationSeconds, 144 + 4000);
      expect(res.sectionNames, containsAll(['Reading', 'Meditation']));
      
      final synth = jsonDecode(res.synthesizedJson) as Map<String, dynamic>;
      final synthClients = synth['clients'] as List<dynamic>;
      expect(synthClients.length, 2);
      final reading = synthClients.firstWhere((c) => c['name'] == 'Reading');
      expect(reading['totalSecsToday'], 144);
      expect(reading['reps'], 27);
    });

    // 3. Real Summary CSV generated by ESP32 and CsvExportService
    const realSummaryCsv = '''
Section_ID,Section_Name,Today_Seconds,Today_Hours,AllTime_Total_Seconds,AllTime_Hours,Reps_Logged,Mastery_Level,Current_Streak_Days,Longest_Streak_Days,Last_Updated
5,"Reading",144,0.04,7344,2.04,27,"LEVEL 1",1,1,"2026-09-12 10:01:23"
6,"Meditation",600,0.17,1800,0.50,3,"LEVEL 0",1,1,"2026-09-12 10:01:23"
''';

    test('Real Summary CSV exported from device or app parses correctly', () {
      final res = DataImportService.parseAndValidate(realSummaryCsv);
      expect(res.isValid, isTrue, reason: res.errorMessage);
      expect(res.sectionCount, 2);
      expect(res.sessionCount, 2);
      expect(res.totalDurationSeconds, 7344 + 1800);
      expect(res.sectionNames, containsAll(['Reading', 'Meditation']));

      final synth = jsonDecode(res.synthesizedJson) as Map<String, dynamic>;
      final synthClients = synth['clients'] as List<dynamic>;
      final reading = synthClients.firstWhere((c) => c['name'] == 'Reading');
      expect(reading['totalSecsToday'], 144);
      expect(reading['reps'], 27);
    });

    // 4. End-to-end export from CsvExportService -> DataImportService round-trip
    test('CsvExportService output imports seamlessly into DataImportService', () async {
      const mockStatus = DeviceStatus(
        currentStreak: 4,
        longestStreak: 10,
        clients: [
          ClientSection(
            id: 1,
            name: 'Deep Code',
            totalSecondsToday: 3600,
            reps: 12,
            history: [
              HistoryEntry(
                timestamp: '2026-09-11 10:00:00',
                date: '11 Sep 2026',
                seconds: 5400,
                reps: 8,
              ),
            ],
          ),
        ],
      );

      final exportedSessions = await CsvExportService.generateSessionsCsv(status: mockStatus);
      final parsedSessions = DataImportService.parseAndValidate(exportedSessions);
      expect(parsedSessions.isValid, isTrue, reason: parsedSessions.errorMessage);
      expect(parsedSessions.sectionNames, contains('Deep Code'));

      final exportedSummary = await CsvExportService.generateSummaryCsv(status: mockStatus);
      final parsedSummary = DataImportService.parseAndValidate(exportedSummary);
      expect(parsedSummary.isValid, isTrue, reason: parsedSummary.errorMessage);
      expect(parsedSummary.sectionNames, contains('Deep Code'));

      final exportedJson = await CsvExportService.generateBackupJson(status: mockStatus);
      final parsedJson = DataImportService.parseAndValidate(exportedJson);
      expect(parsedJson.isValid, isTrue, reason: parsedJson.errorMessage);
      expect(parsedJson.sectionNames, contains('Deep Code'));
      expect(parsedJson.currentStreak, 4);
      expect(parsedJson.longestStreak, 10);
    });

    // 5. Markdown code-fenced input (e.g. copied from chat or markdown document)
    test('Markdown codeblock-wrapped JSON and CSV are cleaned and parsed', () {
      const wrappedJson = '''
```json
{
  "clients": [
    {
      "id": 1,
      "name": "Neural Protocol",
      "totalSecsToday": 1800,
      "reps": 4,
      "history": []
    }
  ]
}
```
''';
      final resJson = DataImportService.parseAndValidate(wrappedJson);
      expect(resJson.isValid, isTrue, reason: resJson.errorMessage);
      expect(resJson.sectionNames, contains('Neural Protocol'));

      const wrappedCsv = '''
```csv
Full_Timestamp,Date,Focus_Section,Duration_Formatted,Duration_Seconds,Reps_Completed,Mastery_Level
"2026-09-12 10:00:00","12 Sep 2026","Circuit Design","1h 00m",3600,10,"LEVEL 1"
```
''';
      final resCsv = DataImportService.parseAndValidate(wrappedCsv);
      expect(resCsv.isValid, isTrue, reason: resCsv.errorMessage);
      expect(resCsv.sectionNames, contains('Circuit Design'));
    });

    // 6. Malformed and edge case inputs
    test('Invalid JSON and CSV produce clear diagnostic messages', () {
      final invalidJson = DataImportService.parseAndValidate('{"clients": [');
      expect(invalidJson.isValid, isFalse);
      expect(invalidJson.errorMessage, contains('JSON parse error'));

      final unknownFormat = DataImportService.parseAndValidate('Just random plain text without commas');
      expect(unknownFormat.isValid, isFalse);
      expect(unknownFormat.errorMessage, contains('Unrecognized format'));
    });

    // 7. Lossless JSON v2 Export with Metadata & Sanity
    test('generateLosslessJsonBackup generates canonical JSON v2 with enriched manifest metadata', () {
      const mockStatus = DeviceStatus(
        currentStreak: 6,
        longestStreak: 15,
        globalGoal: 28800,
        clients: [
          ClientSection(
            id: 10,
            name: 'Kernel Engineering',
            totalSecondsToday: 7200,
            reps: 18,
            history: [
              HistoryEntry(
                timestamp: '2026-09-12 14:00:00',
                date: '12 Sep 2026',
                seconds: 3600,
                reps: 6,
              ),
              HistoryEntry(
                timestamp: '2026-09-11 11:00:00',
                date: '11 Sep 2026',
                seconds: 5400,
                reps: 12,
              ),
            ],
          ),
        ],
      );

      const tasks = [
        TaskItem(id: 1, text: 'Optimize linker scripts', stars: 3, done: true),
        TaskItem(id: 2, text: 'Verify SPI flash speed', stars: 2, done: false),
      ];

      const reminders = [
        ReminderItem(id: 1, text: 'Hydrate every hour'),
      ];

      final jsonString = CsvExportService.generateLosslessJsonBackup(
        status: mockStatus,
        tasks: tasks,
        reminders: reminders,
      );

      final decoded = jsonDecode(jsonString) as Map<String, dynamic>;
      expect(decoded['format'], CsvExportService.backupFormatIdentifier);
      expect(decoded['schemaVersion'], CsvExportService.currentSchemaVersion);
      expect(decoded['appVersion'], CsvExportService.currentAppVersion);
      expect(decoded['currentStreak'], 6);
      expect(decoded['longestStreak'], 15);
      expect(decoded['globalGoal'], 28800);

      // Verify metadata block
      final meta = decoded['metadata'] as Map<String, dynamic>;
      expect(meta['totalSessionsLogged'], 3);
      expect(meta['totalFocusedSeconds'], 7200 + 3600 + 5400);
      expect(meta['totalFocusedHours'], '4.50');
      expect(meta['sectionCount'], 1);
      expect(meta['taskCount'], 2);
      expect(meta['reminderCount'], 1);

      // Verify security sanitization
      expect(decoded.containsKey('password'), isFalse);
      expect(decoded.containsKey('token'), isFalse);
      expect(decoded.containsKey('wifiSsid'), isFalse);
      expect(decoded.containsKey('wifiPassword'), isFalse);
      expect(jsonString.contains('secret'), isFalse);
    });

    // 8. Multi-Table Structured CSV ZIP Archive Generation
    test('generateStructuredCsvZip produces valid archive containing all tables and manifest', () async {
      const mockStatus = DeviceStatus(
        currentStreak: 3,
        longestStreak: 9,
        clients: [
          ClientSection(
            id: 1,
            name: 'Firmware Design',
            totalSecondsToday: 3600,
            reps: 5,
            history: [
              HistoryEntry(timestamp: '2026-09-12 12:00:00', date: '12 Sep 2026', seconds: 3600, reps: 5),
            ],
          ),
        ],
      );

      const tasks = [TaskItem(id: 1, text: 'Build production image', stars: 3, done: false)];
      const reminders = [ReminderItem(id: 1, text: 'Clean solder station')];

      final zipBytes = await CsvExportService.generateStructuredCsvZip(
        status: mockStatus,
        tasks: tasks,
        reminders: reminders,
      );

      expect(zipBytes, isNotEmpty);
      final archive = ZipDecoder().decodeBytes(zipBytes);
      final fileNames = archive.files.map((f) => f.name).toList();

      expect(fileNames, containsAll([
        'manifest.json',
        'sessions.csv',
        'summary.csv',
        'tasks.csv',
        'reminders.csv',
        'settings.csv',
      ]));

      // Verify manifest.json in zip
      final manifestFile = archive.findFile('manifest.json')!;
      final manifestMap = jsonDecode(utf8.decode(manifestFile.content as List<int>)) as Map<String, dynamic>;
      expect(manifestMap['archiveFormat'], 'cranium_structured_csv_archive');
      expect(manifestMap['schemaVersion'], 2);
      final metrics = manifestMap['metrics'] as Map<String, dynamic>;
      expect(metrics['sectionsCount'], 1);
      expect(metrics['tasksCount'], 1);
      expect(metrics['remindersCount'], 1);

      // Verify tasks.csv content
      final tasksFile = archive.findFile('tasks.csv')!;
      final tasksCsvContent = utf8.decode(tasksFile.content as List<int>);
      expect(tasksCsvContent, contains('Task_ID,Directive_Text,Priority_Stars,Is_Completed'));
      expect(tasksCsvContent, contains('"Build production image"'));
    });

    // 9. Real-time 4-column diff calculation against currentStatus
    test('DataImportService accurately computes diff metrics against existing device status', () {
      const currentStatus = DeviceStatus(
        currentStreak: 2,
        longestStreak: 5,
        clients: [
          ClientSection(
            id: 1,
            name: 'Audio DSP',
            totalSecondsToday: 1800,
            reps: 4,
            history: [
              HistoryEntry(
                timestamp: '2026-09-12 08:00:00',
                date: '12 Sep 2026',
                seconds: 1800,
                reps: 4,
              ),
            ],
          ),
        ],
      );

      // Incoming payload has Audio DSP (existing) with one matching session and one new session, plus a new section
      final incomingJson = jsonEncode({
        'schemaVersion': 2,
        'clients': [
          {
            'id': 1,
            'name': 'Audio DSP',
            'totalSecsToday': 3600,
            'reps': 8,
            'history': [
              {'timestamp': '2026-09-12 08:00:00', 'date': '12 Sep 2026', 'secs': 1800, 'reps': 4},
              {'timestamp': '2026-09-12 14:00:00', 'date': '12 Sep 2026', 'secs': 1800, 'reps': 4},
            ],
          },
          {
            'id': 2,
            'name': 'Embedded Linux',
            'totalSecsToday': 3600,
            'reps': 6,
            'history': [],
          },
        ],
        'tasks': [
          {'id': 1, 'text': 'Read ALSA docs', 'stars': 3, 'done': false},
        ],
        'reminders': [],
      });

      final result = DataImportService.parseAndValidate(
        incomingJson,
        currentStatus: currentStatus,
      );

      expect(result.isValid, isTrue);
      expect(result.recordsFound, 5); // 2 sections + 2 history + 1 task = 5
      expect(result.recordsAlreadyPresent, 1); // 1 identical session history
      expect(result.recordsToUpdate, 1); // Audio DSP section already present
      expect(result.recordsToAdd, 3); // 1 new section, 1 new session history, 1 task
    });

    // 10. Schema v1 legacy migration to v2
    test('Legacy v1 payload auto-migrates cleanly with default schema attributes', () {
      const legacyV1Payload = '''
{
  "clients": [
    {
      "id": 1,
      "name": "Legacy Tracker Task",
      "totalSecondsToday": 3600,
      "tallyCount": 10,
      "history": []
    }
  ]
}
''';
      final result = DataImportService.parseAndValidate(legacyV1Payload);
      expect(result.isValid, isTrue);
      expect(result.schemaVersion, 1); // detected as v1
      expect(result.sectionNames, contains('Legacy Tracker Task'));

      // Synthesized payload should have canonical keys
      final synth = jsonDecode(result.synthesizedJson) as Map<String, dynamic>;
      final client = (synth['clients'] as List).first as Map<String, dynamic>;
      expect(client['totalSecsToday'], 3600);
      expect(client['reps'], 10);
    });

    // 11. Merge conflict resolution logic
    test('DataImportService parse retains all entities across clients, tasks, and reminders', () {
      const existingClients = [
        ClientSection(
          id: 1,
          name: 'Core Algorithms',
          totalSecondsToday: 1800,
          reps: 2,
          history: [
            HistoryEntry(timestamp: '2026-09-12 10:00:00', date: '12 Sep 2026', seconds: 1800, reps: 2),
          ],
        ),
      ];

      const existingStatus = DeviceStatus(clients: existingClients);

      final incomingPreview = DataImportService.parseAndValidate(
        jsonEncode({
          'clients': [
            {
              'id': 1,
              'name': 'Core Algorithms',
              'totalSecsToday': 3600,
              'reps': 4,
              'history': [
                {'timestamp': '2026-09-12 10:00:00', 'date': '12 Sep 2026', 'secs': 1800, 'reps': 2},
                {'timestamp': '2026-09-12 12:00:00', 'date': '12 Sep 2026', 'secs': 1800, 'reps': 2},
              ],
            },
          ],
        }),
        currentStatus: existingStatus,
      );

      expect(incomingPreview.isValid, isTrue);
      expect(incomingPreview.sectionCount, 1);
      expect(incomingPreview.sessionCount, 2);
    });
  });
}
