#!/usr/bin/env python3
"""
TITIKSHA X1 Web Asset Compressor
Compresses dashboard/index.html into a PROGMEM gzipped C header (include/web_assets.h).
"""

import os
import gzip
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HTML_PATH = os.path.join(PROJECT_ROOT, "dashboard", "index.html")
HEADER_PATH = os.path.join(PROJECT_ROOT, "include", "web_assets.h")

def main():
    if not os.path.exists(HTML_PATH):
        print(f"Error: Could not find {HTML_PATH}")
        sys.exit(1)

    print(f"Reading {HTML_PATH}...")
    with open(HTML_PATH, "rb") as f:
        raw_data = f.read()

    print(f"Compressing ({len(raw_data)} bytes)...")
    compressed = gzip.compress(raw_data, 9)

    hex_bytes = ", ".join(f"0x{b:02x}" for b in compressed)

    header_content = f"""#pragma once
#include <Arduino.h>

// Auto-generated by scripts/compress_web.py
// Source: dashboard/index.html ({len(raw_data)} bytes -> {len(compressed)} bytes gzipped)

const uint32_t DASHBOARD_HTML_GZ_LEN = {len(compressed)};
const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {{
    {hex_bytes}
}};
"""

    print(f"Writing {HEADER_PATH}...")
    with open(HEADER_PATH, "w") as f:
        f.write(header_content)

    ratio = (1.0 - (len(compressed) / len(raw_data))) * 100.0
    print(f"✅ Success! Compressed {len(raw_data)} bytes to {len(compressed)} bytes ({ratio:.1f}% reduction).")

if __name__ == "__main__":
    main()
